import { QueryClient, QueryClientProvider, useQuery } from '@tanstack/react-query'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
const queryClient = new QueryClient()

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <QueryClientProvider client={queryClient}>
          <h1>Using React Query below</h1>
          <Content />
        </QueryClientProvider>
      </main>
    </div>
  )
}

function Content() {
  const { isLoading, error, data } = useQuery({
    queryKey: ['repoData'],
    queryFn: () =>
      fetch('/api/hello').then(res => res.json())
  })
  if (isLoading) return 'Loading...'
  if (error) return 'An error has occurred: ' + error.message

  return (
    <div>
      <h1>{data.name}</h1>
      <p>{data.description}</p>
      <strong>👀 {data.subscribers_count}</strong>{' '}
      <strong>✨ {data.stargazers_count}</strong>{' '}
      <strong>🍴 {data.forks_count}</strong>
    </div>
  )
}